apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::842322303126:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11L3WCXJ3B52U
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::842322303126:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-27T22:22:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1183"
  uid: 330f4559-3f05-4531-8204-642eeb3b99c0
